### ISSUE TITLE
No background on mention user

### ISSUE THREAD

**Issue by Soulivan71** [davart154/Themes#1]
![image](https://github.com/davart154/Themes/assets/36502190/a12651ba-fe29-4649-a8d2-8ba848768ccb)
Ur snippets don't work for user mention.
When I disable the snippets I have the orange default background

**Comment by Soulivan71** [comment]
Hello any idea ?

**Comment by Soulivan71** [comment]
I don't know if its from ur snippets too, but if the mention role is used behind spoiler balise, we don't see the background mention : 
![image](https://github.com/davart154/Themes/assets/36502190/2e683e7c-7d65-4145-a76f-045c5a37a66b)
Its @everyone but its same if its ||@role||

**Comment by Soulivan71** [comment]
@davart154

**Comment by davart154** [comment]
I haven't looked at this snippet in awhile, I might redo it or change something up to clean it up better. Thanks for pointing this stuff out.

**Comment by Soulivan71** [comment]
Thx u to let me know

**Comment by Soulivan71** [comment]
Hello any updates ?

**Comment by Soulivan71** [comment]
Hello any updates ? @davart154
