### ISSUE TITLE
Icons are broken

### ISSUE THREAD

**Issue by mak448a** [davart154/Themes#11]
I stuck `@import url(https://davart154.github.io/Themes/Icon%20Revert%202023/2023%20Icon%20Revert.css);` into betterdiscord, and it worked for a while. Now it doesn't work anymore. Could you please update it for the latest version of Discord? Thank you.

**Comment by mak448a** [comment]
![Uploading image.png…]()

**Comment by Baumx1234** [comment]
Same here, tried different links and also to import it locally, not working.

**Comment by thisRedH** [comment]
3a8b9a6 fixes it partially, but you cant see if youre muted. The bar through the icons is missing.

**Comment by ErnestoTheGamer** [comment]
+1 on the muted/deafened icons not working correctly.

**Comment by heyitzrare** [comment]
+1 on mute/deafen icons + chatbox icons being broken. Running Vencord

**Comment by ljcool2006** [comment]
![image](https://github.com/davart154/Themes/assets/51834343/92f5a1b0-8618-4eec-813a-9a33c0b1d4d3)
these icons are still the new ones

**Comment by ljcool2006** [comment]
> ![image](https://private-user-images.githubusercontent.com/51834343/314903077-92f5a1b0-8618-4eec-813a-9a33c0b1d4d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1Njc0NzMsIm5iZiI6MTcxMTU2NzE3MywicGF0aCI6Ii81MTgzNDM0My8zMTQ5MDMwNzctOTJmNWExYjAtODYxOC00ZWVjLTgxM2EtOWEzM2MwYjFkNGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDE5MTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNzBiMTA5ZWNiODdiNjZlMzgyYTI5YjZmNzJmYjk4Y2NkNjEwNTY5Mjk1YjJjMTczNzZkYjIwN2YzYjBlZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pDI-EnUDVZnE7JIOPPupaQlIgai0aP6WBbBymJ7T1nQ) these icons are still the new ones
i forgot to mention that the noise suppression icon is incorrect
