### ISSUE TITLE
Some icons are still broken

### ISSUE THREAD

**Issue by heyitzrare** [davart154/Themes#13]
Pause button in the media player
![image](https://github.com/davart154/Themes/assets/64173559/7091a1b5-e464-4e22-aa38-829654abf6c3)

Send Message button
![image](https://github.com/davart154/Themes/assets/64173559/50612d17-154b-4fc8-9317-687b1645cbf4)

Additional buttons added by Vencord plugins (GIFs and Silent Typing button both take the middle Gift button's texture - GIFs is on the right)
![image](https://github.com/davart154/Themes/assets/64173559/0d408fd9-87b1-4859-8434-40155003edb7)

**Comment by thisRedH** [comment]
The fix for the Vencord Icons is in the Pull request #12, since they always get the .vc-chatbar-button class using the Vencord plugin API.

**Comment by thisRedH** [comment]
https://github.com/davart154/Themes/pull/14 fixes the Vencord Icons

**Comment by thisRedH** [comment]
The play/pause buttons Arent broken for me. Probably another Theme you are using?
![image](https://github.com/davart154/Themes/assets/114261766/59e0733b-aaa6-4f24-a773-c5dcaf522f23)
![image](https://github.com/davart154/Themes/assets/114261766/7bc5a900-f1ec-4772-985a-03f2d9b54e70)

**Comment by heyitzrare** [comment]
> #14 fixes the Vencord Icons and send message buttons

Implemented in a local version, the Silent Typing button seems to be broken
![image](https://github.com/davart154/Themes/assets/64173559/7df4ddb1-be72-4157-a099-ef59b9d23001)


> The play/pause buttons Arent broken for me. Probably another Theme you are using? ![image](https://private-user-images.githubusercontent.com/114261766/318166734-0a38ad3d-14a9-48a0-b181-68a8ed566b72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3ODczODcsIm5iZiI6MTcxMTc4NzA4NywicGF0aCI6Ii8xMTQyNjE3NjYvMzE4MTY2NzM0LTBhMzhhZDNkLTE0YTktNDhhMC1iMTgxLTY4YThlZDU2NmI3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQwODI0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzg5NmFlN2Y2YTNkNGFjMjYyODQ4OGJlNTExYjk1NWExOTBjNGVmY2VlNzM4NDdhMmNmZGYxNWViNDk3NjE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JQRXfxAW9quxxJMtxmv9cNa7kFjpHb4z3nGob_ZP9Io) ![image](https://private-user-images.githubusercontent.com/114261766/318166745-afc5438a-56c9-44c8-87a0-99cda95b827b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3ODczODcsIm5iZiI6MTcxMTc4NzA4NywicGF0aCI6Ii8xMTQyNjE3NjYvMzE4MTY2NzQ1LWFmYzU0MzhhLTU2YzktNDRjOC04N2EwLTk5Y2RhOTViODI3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQwODI0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2FjNmRlNGM0MDliZDUyMTZiNTkyOTVmZDU5OTI0NjFiM2YxYjY2ZjhkMzg1MTc0NTVhMmY2YTcwYzZkZjQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5x_c9DnH_zctXCaOw-S8s9YXjaOFywqJKKM_cf0NxtY)

Turned off all themes, pause button is still broken :(

**Comment by thisRedH** [comment]
> Implemented in a local version, the Silent Typing button seems to be broken

mhh thats weird... I dont have this problem
![image](https://github.com/davart154/Themes/assets/114261766/4b94a9d1-6d71-45df-80a5-b50907de2927)

**Comment by thisRedH** [comment]
ups, wrong plugin... but still, works for me
![image](https://github.com/davart154/Themes/assets/114261766/76d4b78a-88b6-410b-80f2-44c0890fd2e7)

**Comment by thisRedH** [comment]
@heyitzrare maybe try updating or reinstalling discord and vencord?

**Comment by heyitzrare** [comment]
yeah so the local version I was using was borked, online ver did in fact fix it

**Comment by thisRedH** [comment]
Fixed [here](https://github.com/thisRedH/DiscordThemes)
