### ISSUE TITLE
Gifs picker btn + send msg btn

### ISSUE THREAD

**Issue by Eight-P** [davart154/Themes#15]
The `:nth-last-child(3)` for the GIFs btn selector won't work when the "send message button" is present, as it will shift the button's position to `:nth-last-child(4)`.
https://github.com/davart154/Themes/blob/main/Icon%20Revert%202023/2023%20Icon%20Revert.css#L1116

Also why not just stick to selecting them by their paths?

**Comment by thisRedH** [comment]
Already said in #13 and fixed in #14 (if @davart154 accepts it...)

**Comment by thisRedH** [comment]
Fixed [here](https://github.com/thisRedH/DiscordThemes)
