### ISSUE TITLE
Server mute and muting others is broken in Icon Revert 2023

### ISSUE THREAD

**Issue by thisRedH** [davart154/Themes#19]
Server mute and muting others is broken in Icon Revert 2023

![image](https://github.com/davart154/Themes/assets/114261766/6e6c36f6-8f7f-4f35-b573-1fd766128cc1)
![image](https://github.com/davart154/Themes/assets/114261766/6a2f17e3-85c8-4551-9bf1-1cb9d5e77339)

**Comment by davart154** [comment]
thanks, i'll check it out
