### ISSUE TITLE
Audio Refresh

### ISSUE THREAD

**Issue by lolpowerluke** [davart154/Themes#24]
Can I use your audio refresh snippet in my theme?
I edited it lightly to fit in but since most of the code is yours I thought I'd ask.
The theme I want to add it to is my [alan walker theme](https://github.com/lolpowerluke/bd-themes/tree/main/AlanWalkerTheme)

**Comment by lolpowerluke** [comment]
also, sidenote, just adding the import doesnt work, so maybe look into that

**Comment by davart154** [comment]
Hi, yes you can use this in your theme if you want to.
As for the import not working, I'm going to have to figure it out. I think github just straight up decided to not create a proper pages link for some reason so I'll try and get that fixed.

**Comment by lolpowerluke** [comment]
alr ty
