### ISSUE TITLE
Fake Deco

### ISSUE THREAD

**Issue by iGetUploaded** [davart154/Themes#3]
Im not sure if its a theme problem or what but when I look in chat the fake decos look like this 
![image](https://github.com/davart154/Themes/assets/54633753/18ba9f0e-9c2f-4cc1-9d5b-d5a43691975d)

But on the member side & when u click on the user and user panel it looks normal

**Comment by davart154** [comment]
Seems to be a theme issue. What's the name of the theme?

**Comment by iGetUploaded** [comment]
> Seems to be a theme issue. What's the name of the theme?

Srry for late response its Midnight
