### ISSUE TITLE
Icon color is grey not light red for muted and deafened

### ISSUE THREAD

**Issue by AmberRoseZA** [davart154/Themes#8]
Icon color is grey not light red for muted and deafened
how its supposed to look:
![image](https://github.com/davart154/Themes/assets/13422754/eaba9dc3-553c-4ebe-ad23-854bc358d716)

How it looks:
 
![image](https://github.com/davart154/Themes/assets/13422754/c44a4ac0-aa7e-40c0-a631-e8eb9a217e27)

**Comment by huskyon9** [comment]
The GameActivityToggle plugin icon is changed to new icon, i think your css can include this old icon too. it change to new icon after discord updated. Thank you
![image](https://github.com/davart154/Themes/assets/124596711/c5aabed8-29e4-4e4f-a056-d110c21058d8)
