### ISSUE TITLE
❤️ Thank you!

### ISSUE THREAD

**Issue by madebylydia** [davart154/Themes#9]
Hey there!
Just a kind message to thank you for the hard work you're putting into your theme, you're doing such an awesome job I can't stop coming back to your themes. :)
It is a shame, only a poor number of themes do not work anymore, but I'm so glad yours are part of the most maintained ones!

Thank you for your awesome work! Much love.

**Comment by davart154** [comment]
Hi! Thanks for the kind words. I'm glad that you are enjoying my stuff. I enjoy working on this stuff a lot and work toward making sure everything's clean and easy to use. Happy new year!
